on:
  push:
    tags:
      - '*'
name: Build and push image
jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Buf registry
        uses: docker/login-action@v1
        with:
          registry: plugins.buf.build
          username: ${{ secrets.BUF_USER_NAME }}
          password: ${{ secrets.BUF_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            plugins.buf.build/boostport/validate${{ env.TAG }}