on:
  push:
    branches:
      - main
  pull_request:
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test building image
        uses: docker/build-push-action@v2